export const isValidIndonesianLocation = (location: string): boolean => {
    // Define the Indonesian locations
    const indonesianLocations: Set<string> = new Set([
        "Jakarta",
        "Banda Aceh",
        "Sabang",
        "Medan",
        "Binjai",
        "Padang Sidempuan",
        "Sibolga",
        "Tebing Tinggi",
        "Padang",
        "Solok",
        "Bukittinggi",
        "Payakumbuh",
        "Pekanbaru",
        "Dumai",
        "Batam",
        "Tanjung Pinang",
        "Karimun",
        "Lingga",
        "Natuna",
        "Jambi",
        "Sungai Penuh",
        "Palembang",
        "Lubuklinggau",
        "Pagar Alam",
        "Bengkulu",
        "Bandar Lampung",
        "Metro",
        "Jakarta Pusat",
        "Jakarta Utara",
        "Jakarta Selatan",
        "Jakarta Timur",
        "Jakarta Barat",
        "Bandung",
        "Bogor",
        "Bekasi",
        "Depok",
        "Cimahi",
        "Semarang",
        "Surakarta",
        "Salatiga",
        "Pekalongan",
        "Tegal",
        "Yogyakarta",
        "Surabaya",
        "Malang",
        "Kediri",
        "Probolinggo",
        "Blitar",
        "Denpasar",
        "Singaraja",
        "Mataram",
        "Bima",
        "Kupang",
        "Maumere",
        "Ende",
        "Pontianak",
        "Singkawang",
        "Palangka Raya",
        "Kotawaringin Barat",
        "Kotawaringin Timur",
        "Banjarmasin",
        "Banjarbaru",
        "Samarinda",
        "Balikpapan",
        "Bontang",
        "Tarakan",
        "Nunukan",
        "Manado",
        "Bitung",
        "Tomohon",
        "Palu",
        "Donggala",
        "Makassar",
        "Parepare",
        "Palopo",
        "Kendari",
        "Baubau",
        "Mamuju",
        "Gorontalo",
        "Ambon",
        "Tual",
        "Ternate",
        "Tidore",
        "Jayapura",
        "Sorong",
        "Merauke",
        "Manokwari",
        "Fakfak",
        "Raja Ampat",
        "Langsa",
        "Lhokseumawe",
        "Wamena",
        "Ruteng",
        "Labuan Bajo",
        "Tanjung Selor",
        "Sampit",
        "Muara Teweh",
        "Luwuk",
        "Tolitoli",
        "Cirebon",
        "Purwokerto",
        "Banjar",
        "Batu",
        "Gunungsitoli",
        "Kotamobagu",
        "Madiun",
        "Magelang",
        "Mojokerto",
        "Padangpanjang",
        "Pariaman",
        "Pasuruan",
        "Pematangsiantar",
        "Prabumulih",
        "Sawahlunto",
        "Subulussalam",
        "Sukabumi",
        "Tanjungbalai",
        "Tanjungpinang",
        "Tasikmalaya",
        "Tidore Kepulauan"
    ]);

    // Normalize location name
    const normalizedLocation: string = location.trim();

    // Check if the location is in the set of valid locations
    return indonesianLocations.has(normalizedLocation);
}
